[project]
site_name = "JScript Panel"
copyright = "Copyright &copy; 2026 marc2003"
extra_css = ["stylesheets/extra.css"]
nav = [
	{ "Overview" = [
		{ "Overview" = [
			"index.md"
		]},
		{ "Requirements & Installation" = "installation.md" },
		{ "Configuration Window" = "configuration-window.md" },
		{ "Tips" = "tips.md" },
		{ "Preprocessors" = "preprocessors.md" },
	]},
	{ "API" = [
		{ "API" = [
			{ "Flags" = "api/flags.md" }
		]},
		{ "Callbacks " = [
			{ "Overview" = "api/callbacks/index.md" },
			{ "Component" = "api/callbacks/component.md" },
			{ "Windows" = "api/callbacks/windows.md" },
			{ "foobar2000" = "api/callbacks/foobar2000.md" },
		]},
		{ "Namespaces" = [
			{ "console" = "api/namespaces/console.md" },
			{ "fb" = "api/namespaces/fb.md" },
			{ "playback" = "api/namespaces/playback.md" },
			{ "plman" = "api/namespaces/plman.md" },
			{ "utils" = "api/namespaces/utils.md" },
			{ "window" = "api/namespaces/window.md" },
		]},
		{ "Interfaces" = [
			{ "IAudioChunk" = "api/interfaces/IAudioChunk.md" },
			{ "IContextMenuManager" = "api/interfaces/IContextMenuManager.md" },
			{ "IDropAction" = "api/interfaces/IDropAction.md" },
			{ "IFileInfo" = "api/interfaces/IFileInfo.md" },
			{ "IJSBitmap" = "api/interfaces/IJSBitmap.md" },
			{ "IJSGraphics" = "api/interfaces/IJSGraphics.md" },
			{ "IJSImage" = "api/interfaces/IJSImage.md" },
			{ "IMainMenuManager" = "api/interfaces/IMainMenuManager.md" },
			{ "IMenuObj" = "api/interfaces/IMenuObj.md" },
			{ "IMetadbHandle" = "api/interfaces/IMetadbHandle.md" },
			{ "IMetadbHandleList" = "api/interfaces/IMetadbHandleList.md" },
			{ "IPlayingItemLocation" = "api/interfaces/IPlayingItemLocation.md" },
			{ "ITextLayout" = "api/interfaces/ITextLayout.md" },
			{ "ITitleFormat" = "api/interfaces/ITitleFormat.md" },
			{ "ITooltip" = "api/interfaces/ITooltip.md" },
		]}
	]},
	{ "Guides" = [
		{ "Fonts" = "guides/fonts.md" },
		{ "Styling Ranges Of Text" = "guides/styling-ranges-text.md" },
		{ "$font & $rgb" = "guides/font-rgb.md" },
		{ "Country Flags" = "guides/country-flags.md" },
		{ "Gradients" = "guides/gradients.md" },
		{ "Web Requests" = "guides/web-requests.md" },
	]},
	{ "Gallery" = [
		{ "Gallery" = [
			"gallery/index.md"
		]},
		{ "Album Art" = "gallery/album-art.md" },
		{ "Allmusic" = "gallery/allmusic.md" },
		{ "Images" = "gallery/images.md" },
		{ "JS Playlist" = "gallery/jsplaylist.md" },
		{ "Last.fm Bio" = "gallery/lastfm-bio.md" },
		{ "Last.fm Info" = "gallery/lastfm-info.md" },
		{ "MusicBrainz" = "gallery/musicbrainz.md" },
		{ "Play Log" = "gallery/play-log.md" },
		{ "Properties + Other Info" = "gallery/properties-other-info.md" },
		{ "Seekbars + Buttons" = "gallery/seekbar-button.md" },
		{ "Smooth Browser" = "gallery/smooth-browser.md" },
		{ "Smooth Playlist" = "gallery/smooth-playlist.md" },
		{ "Smooth Playlist Manager" = "gallery/smooth-playlist-manager.md" },
		{ "Spectrogram Seekbar" = "gallery/spectrogram-seekbar.md" },
		{ "Text Display" = "gallery/text-display.md" },
		{ "Text Reader" = "gallery/text-reader.md" },
		{ "Thumbs" = "gallery/thumbs.md" },
		{ "VU Meter" = "gallery/vu-meter.md" },
	]}
]

[project.theme]
palette.accent = "indigo"
palette.primary = "indigo"
features = [
	"content.code.copy",
	"navigation.indexes",
	"navigation.sections",
	"navigation.tabs",
	"navigation.tabs.sticky",
	"navigation.top"
]

[project.theme.icon]
logo = "material/language-javascript"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/marc2k3"

[project.markdown_extensions.admonition]

[project.markdown_extensions.pymdownx.highlight]

[project.markdown_extensions.pymdownx.keys]

[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
